services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Select storage provider: memory | file | couchdb
      - STORAGE_PROVIDER=file
      # File storage settings (only used when STORAGE_PROVIDER=file)
      - USERS_FILE_PATH=/data/users.json
      # CouchDB settings (only used when STORAGE_PROVIDER=couchdb)
      - COUCHDB_URL=http://admin:password@couchdb:5984
      - COUCHDB_DB=users
    volumes:
      # Persist users.json when using file storage
      - ./data:/data
    depends_on:
      - couchdb
  couchdb:
    image: couchdb:3
    restart: unless-stopped
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:
